In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:4]

array([1, 2, 3])

In [7]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [8]:
arr[:11]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr[0:5] = 100

In [10]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [13]:
arr = np.arange(0, 11)

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
slice_of_arr = arr[0:6]

In [16]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [17]:
slice_of_arr[:] = 99

In [18]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [20]:
arr # Изменение в slice_of_arr вляет также как аrr, то есть она не копирует arr , а просто ссылается 

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
arr_copy = arr.copy() # Что б копировать мы должны использoвать функццию   .copy()  

In [23]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [24]:
arr_copy[:] = 100

In [25]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [26]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [27]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [39]:
arr_2d 

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [40]:
# Есть два варианта аргумента из массива.В первом мы изпользуем две скопки , а во втором вместо двух используем запятую

In [41]:
arr_2d[1][2]

30

In [42]:
arr_2d[1, 2]

30

In [45]:
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

In [58]:
ar = np.arange(1, 11)

In [59]:
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
ar > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [61]:
bool_ar = ar > 5

In [62]:
bool_ar

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [63]:
ar[bool_ar]

array([ 6,  7,  8,  9, 10])

In [64]:
ar[ar>5]

array([ 6,  7,  8,  9, 10])

In [65]:
ar[ar<3]

array([1, 2])

In [68]:
arr_2d = np.arange(50).reshape(5,10)

In [69]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [75]:
arr_2d[3:,4:6]

array([[34, 35],
       [44, 45]])

In [76]:
arr = np.arange(0, 11)

In [77]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [79]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [80]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [81]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [82]:
arr ** arr

array([         1,          1,          4,         27,        256,
             3125,      46656,     823543,   16777216,  387420489,
       1410065408], dtype=int32)

In [83]:
arr / arr

D:\Nurgali\anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [84]:
1 / arr

D:\Nurgali\anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])