In [1]:
my_list = [1, 2, 3]

In [2]:
import numpy as np

In [7]:
arr = np.array(my_list)

In [8]:
arr

array([1, 2, 3])

In [9]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
kek = np.array(my_mat)

In [13]:
kek

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones(4)

array([1., 1., 1., 1.])

In [21]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
np.linspace(0, 9, 3)

array([0. , 4.5, 9. ])

In [37]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
np.random.rand(5)

array([0.81171995, 0.76445162, 0.77299905, 0.53107649, 0.50673862])

In [40]:
np.random.rand(5,5)

array([[0.61777821, 0.90272228, 0.74868454, 0.57275366, 0.63723773],
       [0.22391185, 0.43389862, 0.39677503, 0.0288705 , 0.14677248],
       [0.74735356, 0.48816613, 0.42274008, 0.22418644, 0.20401301],
       [0.32998706, 0.19226435, 0.30695616, 0.22677849, 0.35464596],
       [0.39340065, 0.83755321, 0.48691424, 0.07473635, 0.98087073]])

In [48]:
np.random.randn(5)

array([0.78752382, 0.19475753, 0.20868542, 0.90825846, 0.2706374 ])

In [43]:
np.random.randn(5, 5)

array([[ 0.41929036, -0.26958801, -0.3983428 , -0.02059541,  1.04597511],
       [ 0.27251756, -0.67683011, -0.36023535,  0.27884973,  0.62259238],
       [-0.2134641 ,  1.22251837, -0.69300181,  1.08370266, -2.22661048],
       [-0.49932757,  0.43893412, -1.00584698, -0.39309305,  0.42589603],
       [ 0.53811252,  0.56770122, -0.56790854, -0.35411008,  0.3617135 ]])

In [49]:
np.random.randint(0, 100)

27

In [50]:
np.random.randint(0, 100, 10)

array([42, 17, 95, 44, 30, 28, 73, 38,  7,  0])

In [52]:
arr = np.arange(25)

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [54]:
ranarr = np.random.randint(0, 50, 10)

In [55]:
ranarr

array([ 5, 13, 41, 48,  5, 30, 29, 48, 30, 48])

In [68]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [60]:
ranarr.max()

48

In [61]:
ranarr.min()

5

In [62]:
ranarr

array([ 5, 13, 41, 48,  5, 30, 29, 48, 30, 48])

In [63]:
ranarr.argmax() #показывает индекс макс. аргумента в массиве

3

In [64]:
ranarr.argmin()

0

In [69]:
arr.shape #если хотите выяснить форму 

(25,)

In [70]:
arr = arr.reshape(5, 5)

In [71]:
arr.shape

(5, 5)

In [73]:
arr.dtype #data type

dtype('int32')

In [74]:
from numpy.random import randint

In [75]:
randint(0, 50)

47